### ISSUE TITLE
losalamos github organization rename

### ISSUE THREAD

**Issue by junghans** [lanl/support#5]
Hi @losalamos/all,

On January 14-15, the https://github.com/losalamos organization will be renamed to https://github.com/lanl. All URLs of the form `https://github.com/losalamos/repo/...` will be renamed to `https://github.com/lanl/repo/...`  Although the old names will automatically forward to the new ones, we recommend you switch over to the new URLs in all your documentation (e.g., your README file).  Besides that, no action is required on your side.

We will do the transition over the weekend of January 14th/15th, so if you have any concerns please speak up before that.

Cheers,

@losalamos/admin

**Comment by jlconlin** [comment]
Will all of us be automatically added to the lanl organization or do we need to do that manually?

Jeremy

**Comment by junghans** [comment]
Yes, all the metadata (memberships, teams, wikis, issues etc.) will transferred along with the repos.

**Comment by certik** [comment]
@junghans perfect! Thank you for doing that and merging the organizations.

**Comment by millerta** [comment]
Hi Christoph,

Just to confirm, after Jan 15, 

   https://github.com/losalamos/LaGriT
will become
   https://github.com/lanl/LaGriT


Also, can we use Github + Asana?
Is there support for setting this up?


Terry A. Miller
Mesh Generation and Software
SFT / Computational Earth Science
tamiller@lanl.gov  
505-667-8009

**Comment by junghans** [comment]
Yep, the “losalamos” namespace will become “lanl” and if you happen to go to the old url it will be forwarded.

For Github/Asana integration see here: https://asana.com/apps/github

Recently github has added projects https://help.github.com/articles/about-projects/, which is basically a light-weight replacement for most management tools.

**Comment by millerta** [comment]
Thank you.

Terry A. Miller
Mesh Generation and Software
SFT / Computational Earth Science
tamiller@lanl.gov<mailto:tamiller@lanl.gov>
505-667-8009





On Jan 10, 2017, at 9:11 AM, Christoph Junghans <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep, the “losalamos” namespace will become “lanl” and if you happen to go to the old url it will be forwarded.

For Github/Asana integration see here: https://asana.com/apps/github

Recently github has added projects https://help.github.com/articles/about-projects/, which is basically a light-weight replacement for most management tools.

**Comment by millerta** [comment]
Can you put me in touch with someone who is using the projects tools?

I can not see that it offers task management like Asana and inter-team communications like slack etc.
But maybe I am not seeing it in the descriptions.

We are working on getting permission to use Asana tools.

Terry A. Miller
Mesh Generation and Software
SFT / Computational Earth Science
tamiller@lanl.gov<mailto:tamiller@lanl.gov>
505-667-8009





On Jan 10, 2017, at 9:32 AM, Terry Miller <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you.

Terry A. Miller
Mesh Generation and Software
SFT / Computational Earth Science
tamiller@lanl.gov<mailto:tamiller@lanl.gov><mailto:tamiller@lanl.gov>
505-667-8009





On Jan 10, 2017, at 9:11 AM, Christoph Junghans <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Yep, the “losalamos” namespace will become “lanl” and if you happen to go to the old url it will be forwarded.

For Github/Asana integration see here: https://asana.com/apps/github

Recently github has added projects https://help.github.com/articles/about-projects/, which is basically a light-weight replacement for most management tools.

**Comment by junghans** [comment]
@lanl/all,

the rename is completed and forwards are in place. Please ensure to switch over to the new URLs in all your documentation (e.g., your README file).

Cheers,

@lanl/admin

**Comment by ddaniel** [comment]
Thanks Christoph!   Very much appreciated.
